version: "3"
services:
  es01:
    image: dollarkiller/elasticsearch:7.9.3
    container_name: es01
    hostname: es01
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01,es02
      - discovery.seed_hosts=es02
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8G -Xmx8G"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
    restart: always

  es02:
    image: dollarkiller/elasticsearch:7.9.3
    container_name: es02
    hostname: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8G -Xmx8G"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet
    restart: always

  kibana:
    container_name: kibana01
    hostname: kibana01
    image: docker.elastic.co/kibana/kibana:7.0.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - es01
      - es02
    networks:
      - esnet
    restart: always

  logstash:
    image: logstash:7.10.1
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logs/:/opt/logs/muse/
    depends_on:
      - es01
      - es02
    networks:
      - esnet
    restart: always

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:
